### ISSUE TITLE
NPE when switching survey responses

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#21]
This issue was reported by @MarkGisi while testing out the new release which includes the ability to select survey versions.

> Logged in. Came up with version 1.1. I selected version 1.0 and got following error: [graphic of unexpected error occurred]
 
> I clicked on the “Ok” button and the msg  went away. I was able to get the 1.0 form. I was able to toggle between 1.0 and 1.1 with no problem thereafter. No more error msg. 

Below is a stack trace from the server log:
```java.lang.NullPointerException
	at org.openchain.certification.dbdao.SurveyResponseDao._updateSurveyResponseAnswers(SurveyResponseDao.java:558)
	at org.openchain.certification.dbdao.SurveyResponseDao.updateSurveyResponseAnswers(SurveyResponseDao.java:540)
	at org.openchain.certification.UserSession.updateAnswers(UserSession.java:608)
	at org.openchain.certification.CertificationServlet.doPost(CertificationServlet.java:403)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1201)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by goneall** [comment]
From looking at the stack trace, the currentResponse looks like it is not either initialized or set in the UserSession.   Suggest next steps is to add some defensive checks for null pointers in the _updateSurveyResponseAnswers method and walk through the UserSession code that should initialize the response.

**Comment by goneall** [comment]
I haven't heard anything on this issue for over 2 years - closing as stale.
