### ISSUE TITLE
Null pointer exception when reseting to a recently uploaded new version of the spec

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#27]
The following steps caused an NPE exception:

- Upload a new version of the specification
- Reset the survey and select the latest version

Below is the stack trace:
```
java.lang.NullPointerException
	at org.openchain.certification.dbdao.SurveyResponseDao._updateSurveyResponseAnswers(SurveyResponseDao.java:558)
	at org.openchain.certification.dbdao.SurveyResponseDao.updateSurveyResponseAnswers(SurveyResponseDao.java:540)
	at org.openchain.certification.UserSession.updateAnswers(UserSession.java:608)
	at org.openchain.certification.CertificationServlet.doPost(CertificationServlet.java:403)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) ...
```

The NPE is due to the survey response having a null survey.  I can not find a path through the code where this can occur.

We should add some defensive coding to not update the survey questions when the survey is null.  There is a larger question, however, as to how this got into this state.

It could be a multi-threading issue where the UserSession update is updating the latest survey at the same time as the update questions is being called.  I could not, however, find a path where this would occur even after stepping through the JavaScript code.

**Comment by goneall** [comment]
Resolved in PR #29
